const { strict: assert } = require('node:assert');
const { readFileSync } = require('node:fs');
const ts = require('typescript');
const React = require('react');
const source = readFileSync(`${__dirname}/Game.tsx`, 'utf8');
const ast = ts.createSourceFile('Game.tsx', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
const component = ast.statements.find(node => ts.isFunctionDeclaration(node) && node.name?.text === 'PaperAssetStatus');
assert.ok(component);
const code = ts.transpileModule(`${component.getText(ast)}; exports.render = PaperAssetStatus;`,
  { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.React } }).outputText;
const calls = [];
let attempts = 1;
let currentStatus = 'failed';
const canRetry = () => currentStatus !== 'loading' && currentStatus !== 'ready' && attempts < 3;
const exportsMock = {};
new Function('exports', 'React', 'canRetryPaperAssets', 'loadPaperAssets', code)(exportsMock, React,
  canRetry, options => { attempts++; currentStatus = 'loading'; calls.push(options); return Promise.resolve(); });
const render = status => { currentStatus = status; return exportsMock.render({ status }); };
const button = tree => React.Children.toArray(tree.props.children).find(child => child.type === 'button');
assert.equal(render('ready'), null);
assert.equal(button(render('loading')), undefined);
assert.equal(render('loading').props['aria-busy'], true);
assert.equal(render('loading').props.style.minHeight, undefined);
assert.equal(calls.length, 0, 'render/mount must never retry');
let tree = render('Paper assets failed: branding/wordmark.png — fallback active');
assert.equal(tree.type, 'div');
assert.equal(tree.props.style.position, 'relative', 'reuse existing status banner');
assert.equal(tree.props.style.flexShrink, 0);
assert.equal(tree.props.style.minHeight, 48, 'error banner reserves button height');
assert.equal(tree.props.style.boxSizing, 'border-box');
let action = button(tree);
assert.equal(action.props.children, 'Retry art');
assert.equal(action.props.type, 'button');
assert.ok(action.props.style.minHeight >= 48 && action.props.style.minWidth >= 48);
assert.equal(action.props.style.position, 'absolute', 'button fits reserved error banner');
assert.equal(action.props.disabled, false);
action.props.onClick();
assert.deepEqual(calls, [{ retry: true }]);
action.props.onClick();
assert.equal(calls.length, 1, 'stale click while loading is ignored');
button(render('failed')).props.onClick();
tree = render('failed');
assert.equal(button(tree).props.disabled, true);
assert.match(tree.props.children[0].props.children, /Retry limit reached/);
button(tree).props.onClick();
assert.equal(calls.length, 2);
assert.equal(button(render('failed')).props.disabled, true, 'remount must retain retry bound');
assert.equal(render('ready'), null, 'successful recovery removes banner');
assert.match(source, /<PaperAssetStatus status=\{paperStatus\} \/>/);
assert.equal((source.match(/<PaperAssetStatus\b/g) || []).length, 1);
assert.match(source, /<PaperAssetStatus status=\{paperStatus\} \/>\s*<div ref=\{fieldRef\}/);
const paper = readFileSync(`${__dirname}/paperAssets.ts`, 'utf8');
assert.doesNotMatch(paper.slice(paper.indexOf('export function PaperImage('), paper.indexOf('function paperSkinColor(')), /createElement\('button'/);
console.log('paperAssetStatus regression: passed');
