const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const ts = require('typescript');
const source = readFileSync(`${__dirname}/LeaderboardScreen.tsx`, 'utf8');
const ast = ts.createSourceFile('LeaderboardScreen.tsx', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
const screen = ast.statements.find(node => ts.isFunctionDeclaration(node) && node.name?.text === 'LeaderboardScreen');
assert.ok(screen);
assert.doesNotMatch(source, /fetchTopScores|buildLiveBoard|isFirebaseEnabled|state\.bestWave|state\.monthlyRank/);
assert.doesNotMatch(screen.getText(ast), /setState\(/, 'Reading a preview must not rewrite rank or balances');
assert.match(source, /score\.config/);
assert.match(source, /config\.access !== 'ranked'/);
assert.match(source, /score\.continuedCount !== 0/);
assert.match(source, /score\.ts >= month/);
assert.match(source, /Date\.UTC\(date\.getUTCFullYear\(\), date\.getUTCMonth\(\), 1\)/);
assert.match(source, /selectLocalRankedScores\(state, period, rules, now\)/);
assert.match(source, /score\.seed, score\.speed, score\.engineVersion/);
assert.match(source, /score\.accountScope/);
assert.match(source, /No matching Ranked results/);
assert.match(source, /Demo players, not local rankings/);
assert.match(source, /aria-label="Period"/);
console.log('Leaderboard isolation PASS: local-only, comparable rules, UTC period, no preview writes; executable fixtures in audit-ui.regression.test.cjs.');
